# Details: https://github.com/kirill-markin/repo-to-text
# Syntax: gitignore rules

# Ignore files and directories based on .gitignore rules
gitignore-import-and-ignore: True

# Additional files and directories to ignore for tree and "Contents of ..." sections
ignore-tree-and-content:
    - ".repo-to-text-settings.yaml"
    - "dist"
    - "icon"
    - "LICENSE"
    - "node_modules"
    - "screenshot"

# Additional files to ignore specifically in the "Contents of ..." section
ignore-content:
    - ".gitignore"
    - ".prettierignore"
    - ".prettierrc"
    - "icon"
    - "LICENSE"
    - "package-lock.json"
    - "screenshot"
