# Details: https://github.com/kirill-markin/repo-to-text
# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and "Contents of ..." sections
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"
  - "dist"
  - "node_modules"
  - "icon"

# Ignore files and directories for "Contents of ..." section
ignore-content:
  - "README.md"
  - "LICENSE"
  - ".prettierignore"
  - ".prettierrc"
  - ".gitignore"
